matrix:
  include:
  - language: node_js
    node_js:
    - node
    install:
    - cd v1/client
    - npm install
    test:
    - npm test
    build:
    - npm run build
    before_deploy: npm install -g firebase-tools
    deploy:
    - firebase deploy --token "$FIREBASE_TOKEN"
  - language: python
    services:
    - postgresql
    before_script:
    - cd v1/backend/
    - pip install -r requirements.txt
    script:
    - coverage run --source=blogs manage.py test
    after_success: coveralls
