matrix:
  include:
  - language: node_js
    node_js:
    - node
    install:
    - cd v1/client
    - npm install
    before_script: 
    - CI=false npm run build
    - npm install -g firebase-tools
    script:
    - firebase use default
    - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive 
  - language: python
    services:
    - postgresql
    before_script:
    - cd v1/backend/
    - pip install -r requirements.txt
    script:
    - coverage run --source=blogs manage.py test
    after_success: coveralls
