version: '3'

services:
  blog_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  blog_web:
    build: .
    command: bash -c " 
      python manage.py makemigrations blogs --settings backend.settings-docker &&
      python manage.py migrate --noinput --settings backend.settings-docker &&
      python manage.py test --settings backend.settings-docker && 
      python manage.py runserver --settings backend.settings-docker 0.0.0.0:8005 "
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - blog_db
